"""add ingestion audit tables

Revision ID: 0610046832df
Revises: 8ad6c5e7f3d8
Create Date: 2026-08-01 01:10:04.872475

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0610046832df"
down_revision: str | Sequence[str] | None = "8ad6c5e7f3d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_batches",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_label", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("received_count", sa.Integer(), nullable=False),
        sa.Column("imported_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "failed_count >= 0", name=op.f("ck_ingestion_batches_failed_count_non_negative")
        ),
        sa.CheckConstraint(
            "imported_count >= 0", name=op.f("ck_ingestion_batches_imported_count_non_negative")
        ),
        sa.CheckConstraint(
            "received_count >= 0", name=op.f("ck_ingestion_batches_received_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
            name=op.f("fk_ingestion_batches_platform_id_platforms"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_batches")),
    )
    op.create_index(
        "ix_ingestion_batches_platform_started",
        "ingestion_batches",
        ["platform_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "ingestion_records",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("batch_id", sa.BigInteger(), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("normalized_payload", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("platform_listing_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["ingestion_batches.id"],
            name=op.f("fk_ingestion_records_batch_id_ingestion_batches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["platform_listing_id"],
            ["platform_listings.id"],
            name=op.f("fk_ingestion_records_platform_listing_id_platform_listings"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_records")),
        sa.UniqueConstraint("batch_id", "external_id", name="batch_external_id"),
    )
    op.create_index(
        "ix_ingestion_records_platform_listing",
        "ingestion_records",
        ["platform_listing_id"],
        unique=False,
    )
    op.create_table(
        "listing_match_records",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ingestion_record_id", sa.BigInteger(), nullable=False),
        sa.Column("canonical_listing_id", sa.BigInteger(), nullable=True),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "score BETWEEN 0 AND 1", name=op.f("ck_listing_match_records_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["canonical_listing_id"],
            ["canonical_listings.id"],
            name=op.f("fk_listing_match_records_canonical_listing_id_canonical_listings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_record_id"],
            ["ingestion_records.id"],
            name=op.f("fk_listing_match_records_ingestion_record_id_ingestion_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_match_records")),
        sa.UniqueConstraint(
            "ingestion_record_id", name=op.f("uq_listing_match_records_ingestion_record_id")
        ),
    )
    op.create_index(
        "ix_listing_match_records_canonical",
        "listing_match_records",
        ["canonical_listing_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_listing_match_records_canonical", table_name="listing_match_records")
    op.drop_table("listing_match_records")
    op.drop_index("ix_ingestion_records_platform_listing", table_name="ingestion_records")
    op.drop_table("ingestion_records")
    op.drop_index("ix_ingestion_batches_platform_started", table_name="ingestion_batches")
    op.drop_table("ingestion_batches")
    # ### end Alembic commands ###
