"""add recommendation sessions

Revision ID: 2aa0bd70ef8e
Revises: 0610046832df
Create Date: 2026-08-01 09:54:46.048411

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2aa0bd70ef8e"
down_revision: str | Sequence[str] | None = "0610046832df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendation_sessions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("city", sa.String(length=64), nullable=False),
        sa.Column("check_in", sa.Date(), nullable=False),
        sa.Column("check_out", sa.Date(), nullable=False),
        sa.Column("guest_count", sa.SmallInteger(), nullable=False),
        sa.Column("travel_style", sa.String(length=24), nullable=False),
        sa.Column("budget_total", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("preferred_facilities", sa.JSON(), nullable=False),
        sa.Column("preferred_districts", sa.JSON(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=32), nullable=False),
        sa.Column("request_payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "budget_total IS NULL OR budget_total >= 0",
            name=op.f("ck_recommendation_sessions_budget_non_negative"),
        ),
        sa.CheckConstraint(
            "check_out > check_in", name=op.f("ck_recommendation_sessions_valid_stay_dates")
        ),
        sa.CheckConstraint(
            "guest_count > 0", name=op.f("ck_recommendation_sessions_guest_count_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_sessions")),
        sa.UniqueConstraint("public_id", name=op.f("uq_recommendation_sessions_public_id")),
    )
    op.create_index(
        "ix_recommendation_sessions_city_created",
        "recommendation_sessions",
        ["city", "created_at"],
        unique=False,
    )
    op.create_table(
        "recommendation_results",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("canonical_listing_id", sa.BigInteger(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("total_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("score_breakdown", sa.JSON(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("listing_public_id", sa.String(length=32), nullable=False),
        sa.Column("listing_name", sa.String(length=160), nullable=False),
        sa.Column("district", sa.String(length=64), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("best_rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("platform_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint("`rank` > 0", name=op.f("ck_recommendation_results_rank_positive")),
        sa.CheckConstraint(
            "total_amount >= 0", name=op.f("ck_recommendation_results_total_amount_non_negative")
        ),
        sa.CheckConstraint(
            "total_score BETWEEN 0 AND 100", name=op.f("ck_recommendation_results_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["canonical_listing_id"],
            ["canonical_listings.id"],
            name=op.f("fk_recommendation_results_canonical_listing_id_canonical_listings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["recommendation_sessions.id"],
            name=op.f("fk_recommendation_results_session_id_recommendation_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_results")),
        sa.UniqueConstraint("session_id", "canonical_listing_id", name="session_listing"),
        sa.UniqueConstraint("session_id", "rank", name="session_rank"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recommendation_results")
    op.drop_index("ix_recommendation_sessions_city_created", table_name="recommendation_sessions")
    op.drop_table("recommendation_sessions")
    # ### end Alembic commands ###
