"""add ai parse usage audit

Revision ID: 2e16c8993302
Revises: 959003427db3
Create Date: 2026-08-01 14:37:34.938363

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e16c8993302"
down_revision: str | Sequence[str] | None = "959003427db3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "preference_parse_sessions", sa.Column("prompt_tokens", sa.Integer(), nullable=True)
    )
    op.add_column(
        "preference_parse_sessions", sa.Column("completion_tokens", sa.Integer(), nullable=True)
    )
    op.add_column(
        "preference_parse_sessions", sa.Column("total_tokens", sa.Integer(), nullable=True)
    )
    op.add_column(
        "preference_parse_sessions", sa.Column("ai_error_code", sa.String(length=40), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("preference_parse_sessions", "ai_error_code")
    op.drop_column("preference_parse_sessions", "total_tokens")
    op.drop_column("preference_parse_sessions", "completion_tokens")
    op.drop_column("preference_parse_sessions", "prompt_tokens")
    # ### end Alembic commands ###
