"""create core accommodation tables

Revision ID: 8ad6c5e7f3d8
Revises:
Create Date: 2026-07-31 22:29:15.390765

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ad6c5e7f3d8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canonical_listings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("listing_type", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("province", sa.String(length=64), nullable=False),
        sa.Column("city", sa.String(length=64), nullable=False),
        sa.Column("district", sa.String(length=64), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "latitude BETWEEN -90 AND 90", name=op.f("ck_canonical_listings_latitude_range")
        ),
        sa.CheckConstraint(
            "longitude BETWEEN -180 AND 180", name=op.f("ck_canonical_listings_longitude_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_listings")),
        sa.UniqueConstraint("public_id", name=op.f("uq_canonical_listings_public_id")),
    )
    op.create_index(
        "ix_canonical_listings_location", "canonical_listings", ["city", "district"], unique=False
    )
    op.create_table(
        "facilities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_facilities")),
        sa.UniqueConstraint("code", name=op.f("uq_facilities_code")),
    )
    op.create_table(
        "platforms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("base_url", sa.String(length=512), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platforms")),
        sa.UniqueConstraint("code", name=op.f("uq_platforms_code")),
    )
    op.create_table(
        "listing_facilities",
        sa.Column("canonical_listing_id", sa.BigInteger(), nullable=False),
        sa.Column("facility_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_listing_id"],
            ["canonical_listings.id"],
            name=op.f("fk_listing_facilities_canonical_listing_id_canonical_listings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_listing_facilities_facility_id_facilities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "canonical_listing_id", "facility_id", name=op.f("pk_listing_facilities")
        ),
    )
    op.create_table(
        "platform_listings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("canonical_listing_id", sa.BigInteger(), nullable=True),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "rating IS NULL OR rating BETWEEN 0 AND 5",
            name=op.f("ck_platform_listings_rating_range"),
        ),
        sa.CheckConstraint(
            "review_count >= 0", name=op.f("ck_platform_listings_review_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["canonical_listing_id"],
            ["canonical_listings.id"],
            name=op.f("fk_platform_listings_canonical_listing_id_canonical_listings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
            name=op.f("fk_platform_listings_platform_id_platforms"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_listings")),
        sa.UniqueConstraint("platform_id", "external_id", name="platform_external_id"),
    )
    op.create_index(
        "ix_platform_listings_canonical",
        "platform_listings",
        ["canonical_listing_id"],
        unique=False,
    )
    op.create_table(
        "room_types",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("platform_listing_id", sa.BigInteger(), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("area_m2", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("bed_type", sa.String(length=80), nullable=False),
        sa.Column("bed_count", sa.SmallInteger(), nullable=False),
        sa.Column("max_guests", sa.SmallInteger(), nullable=False),
        sa.Column("is_entire_unit", sa.Boolean(), nullable=False),
        sa.Column("has_private_bathroom", sa.Boolean(), nullable=False),
        sa.Column("view_type", sa.String(length=64), nullable=True),
        sa.Column("cancellation_policy", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "area_m2 IS NULL OR area_m2 > 0", name=op.f("ck_room_types_area_positive")
        ),
        sa.CheckConstraint("bed_count > 0", name=op.f("ck_room_types_bed_count_positive")),
        sa.CheckConstraint("max_guests > 0", name=op.f("ck_room_types_max_guests_positive")),
        sa.ForeignKeyConstraint(
            ["platform_listing_id"],
            ["platform_listings.id"],
            name=op.f("fk_room_types_platform_listing_id_platform_listings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room_types")),
        sa.UniqueConstraint("platform_listing_id", "external_id", name="listing_external_id"),
    )
    op.create_table(
        "price_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("room_type_id", sa.BigInteger(), nullable=False),
        sa.Column("check_in", sa.Date(), nullable=False),
        sa.Column("check_out", sa.Date(), nullable=False),
        sa.Column("guest_count", sa.SmallInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("room_subtotal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cleaning_fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("service_fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("other_fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("price_type", sa.String(length=32), nullable=False),
        sa.Column("promotion_conditions", sa.Text(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("remaining_units", sa.SmallInteger(), nullable=True),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "check_out > check_in", name=op.f("ck_price_snapshots_valid_stay_dates")
        ),
        sa.CheckConstraint(
            "cleaning_fee >= 0", name=op.f("ck_price_snapshots_cleaning_fee_non_negative")
        ),
        sa.CheckConstraint(
            "discount_amount >= 0", name=op.f("ck_price_snapshots_discount_non_negative")
        ),
        sa.CheckConstraint("guest_count > 0", name=op.f("ck_price_snapshots_guest_count_positive")),
        sa.CheckConstraint(
            "other_fee >= 0", name=op.f("ck_price_snapshots_other_fee_non_negative")
        ),
        sa.CheckConstraint(
            "room_subtotal >= 0", name=op.f("ck_price_snapshots_room_subtotal_non_negative")
        ),
        sa.CheckConstraint(
            "service_fee >= 0", name=op.f("ck_price_snapshots_service_fee_non_negative")
        ),
        sa.CheckConstraint(
            "total_amount >= 0", name=op.f("ck_price_snapshots_total_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["room_type_id"],
            ["room_types.id"],
            name=op.f("fk_price_snapshots_room_type_id_room_types"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_snapshots")),
        sa.UniqueConstraint(
            "room_type_id",
            "check_in",
            "check_out",
            "guest_count",
            "captured_at",
            "price_type",
            name="room_query_capture_type",
        ),
    )
    op.create_index(
        "ix_price_snapshots_search",
        "price_snapshots",
        ["room_type_id", "check_in", "check_out", "guest_count"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_price_snapshots_search", table_name="price_snapshots")
    op.drop_table("price_snapshots")
    op.drop_table("room_types")
    op.drop_index("ix_platform_listings_canonical", table_name="platform_listings")
    op.drop_table("platform_listings")
    op.drop_table("listing_facilities")
    op.drop_table("platforms")
    op.drop_table("facilities")
    op.drop_index("ix_canonical_listings_location", table_name="canonical_listings")
    op.drop_table("canonical_listings")
    # ### end Alembic commands ###
