"""add recommendation adjustments and explanations

Revision ID: 959003427db3
Revises: e98b0858110c
Create Date: 2026-08-01 14:01:03.629571

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "959003427db3"
down_revision: str | Sequence[str] | None = "e98b0858110c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendation_adjustments",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("source_session_id", sa.BigInteger(), nullable=False),
        sa.Column("target_session_id", sa.BigInteger(), nullable=False),
        sa.Column("feedback_text", sa.String(length=500), nullable=False),
        sa.Column("applied_changes", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["source_session_id"],
            ["recommendation_sessions.id"],
            name=op.f("fk_recommendation_adjustments_source_session_id_recommendation_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_session_id"],
            ["recommendation_sessions.id"],
            name=op.f("fk_recommendation_adjustments_target_session_id_recommendation_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_adjustments")),
        sa.UniqueConstraint("public_id", name=op.f("uq_recommendation_adjustments_public_id")),
    )
    op.create_index(
        "ix_recommendation_adjustments_source_created",
        "recommendation_adjustments",
        ["source_session_id", "created_at"],
        unique=False,
    )
    op.add_column("recommendation_results", sa.Column("tradeoffs", sa.JSON(), nullable=True))
    op.add_column("recommendation_results", sa.Column("risk_notes", sa.JSON(), nullable=True))
    op.execute("UPDATE recommendation_results SET tradeoffs = JSON_ARRAY()")
    op.execute("UPDATE recommendation_results SET risk_notes = JSON_ARRAY()")
    op.alter_column("recommendation_results", "tradeoffs", existing_type=sa.JSON(), nullable=False)
    op.alter_column("recommendation_results", "risk_notes", existing_type=sa.JSON(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recommendation_results", "risk_notes")
    op.drop_column("recommendation_results", "tradeoffs")
    op.drop_index(
        "ix_recommendation_adjustments_source_created", table_name="recommendation_adjustments"
    )
    op.drop_table("recommendation_adjustments")
    # ### end Alembic commands ###
