"""add preference parse sessions

Revision ID: e98b0858110c
Revises: 2aa0bd70ef8e
Create Date: 2026-08-01 11:29:08.522388

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e98b0858110c"
down_revision: str | Sequence[str] | None = "2aa0bd70ef8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preference_parse_sessions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("parser_name", sa.String(length=40), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("parsed_payload", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("missing_fields", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("confirmed_payload", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_preference_parse_sessions_confidence_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preference_parse_sessions")),
        sa.UniqueConstraint("public_id", name=op.f("uq_preference_parse_sessions_public_id")),
    )
    op.create_index(
        "ix_preference_parse_sessions_status_created",
        "preference_parse_sessions",
        ["status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_preference_parse_sessions_status_created", table_name="preference_parse_sessions"
    )
    op.drop_table("preference_parse_sessions")
    # ### end Alembic commands ###
